### ISSUE TITLE
Help? What is the habitica api key (not token)? 

### ISSUE THREAD

**Issue by Dariuchka** [Kyusung4698/habitica-todoist-pull#1]
I followed the instruction as closely as I could, but my workflows are still not working, can you please help me out? I would love to use todoist to add the tasks as it's much more intuitive

**Comment by Kyusung4698** [comment]
Hey there! I've checked your latest workflow execution, and the HABITICA_API_TOKEN variable seems to have an invalid value. 

```cmd
[habitica] Unable to fetch user task. TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-api-key"]
```

The API token has the following format: `11111111-1111-1111-1111-111111111111`. Please make sure there are no spaces when copy-pasting it. And yes, it's indeed the token; their naming needs to be more consistent 😄

**Comment by Dariuchka** [comment]
Yay, thank you! That worked woohoo!

**Comment by Dariuchka** [comment]
> Eh, actually can I request some more help? The github workflow executed successfully but I put in trial todoist todoes but they are not appearing in habitica side. I refreshed both and tried a not-done-yet todo and a crossed out todo and then refresh => execute manually => refresh to see if it brought it over

**Comment by Kyusung4698** [comment]
The script only syncs to-dos that have a due date set. Otherwise, there are no filters. 
Could you try creating a new to-do, setting it for tomorrow, and then running the script?

**Comment by Dariuchka** [comment]
Oh that's even more perfect, it can set due times too, so I just checked and everything's a-ok! Thanks so much for sharing the repository! I am so excited about this!

**Comment by Kyusung4698** [comment]
Glad it's working now! I'm closing this issue then. Feel free to create a new one if you face any problem.
